add db infrastructure
opensourceways/robot-gitee-software-package pull request #13
Opened 2023-03-15 07:46 UTC by qinsheng99

2023-03-15 08:56 UTC, yangwei999 commented
lgtm

2023-03-15 09:45 UTC, zengchen1024 requested changes

2023-03-15 09:45 UTC, zengchen1024 commented on softwarepkg/infrastructure/repositoryimpl/software_pkg_pr_do.go
> +	Merge     int       `gorm:"column:merge"`
Merged

2023-03-16 01:56 UTC, zengchen1024 requested changes

2023-03-16 01:56 UTC, zengchen1024 commented on softwarepkg/infrastructure/repositoryimpl/software_pkg.go
> +type softwarePkg struct {
it seems that softwarePkg is not used

2023-03-16 02:11 UTC, merged